Repository Netflix/mantis, pull requests merged in 2020-10, with the labels that each got.

#59 Consolidate source jobs
  mantis-source-jobs/README.md
  mantis-source-jobs/mantis-source-job-kafka/build.gradle
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/AbstractAckableTaggingStage.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/AutoAckTaggingStage.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/CustomizedAutoAckTaggingStage.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/QueryableKafkaSourceJob.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/core/TaggedData.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/core/utils/JsonUtility.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/core/utils/SourceJobConstants.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/MQL.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/MQLQueryManager.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/QueryRefCountMap.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/QueryRequestPostProcessor.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/QueryRequestPreProcessor.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/TaggedDataSourceSink.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/TaggedEventFilter.java
  mantis-source-jobs/mantis-source-job-kafka/src/main/resources/META-INF/services/io.mantisrx.runtime.MantisJobProvider
  mantis-source-jobs/mantis-source-job-kafka/src/test/java/io/mantisrx/sourcejob/kafka/QueryableKafkaSourceJobTest.java
  mantis-source-jobs/mantis-source-job-publish/build.gradle
  mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/PushRequestEventSourceJob.java
  mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/core/RequestPostProcessor.java
  mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/core/RequestPreProcessor.java
  mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/core/Utils.java
  mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/stages/EchoStage.java
  mantis-source-jobs/mantis-source-job-publish/src/main/resources/META-INF/services/io.mantisrx.runtime.MantisJobProvider
  settings.gradle
Labels: enhancement

#61 Apply shadow directly within subprojects.
  gradle/shadow.gradle
  mantis-connectors/mantis-connector-iceberg/build.gradle
  mantis-publish/mantis-publish-netty/build.gradle
Labels: bug

#63 Update MQL docs for using [*]
  docs/docs/reference/mql.md
Labels: documentation

#67 Add `LocationProvider` for table location support.
  mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/DefaultIcebergWriter.java
  mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStage.java
Labels: enhancement

#69 Add myself as code owners
  .github/CODEOWNERS
Labels: enhancement

#70 Use Netflix Docker Hub container image registry.
  mantis-control-plane/Dockerfile
  mantis-control-plane/buildDockerImage.sh
  mantis-examples/mantis-examples-mantis-publish-sample/Dockerfile
  mantis-examples/mantis-examples-mantis-publish-web-sample/Dockerfile
  mantis-server/mantis-server-worker/Dockerfile
Labels: enhancement

#72 Add support for specator timers.
  mantis-client/build.gradle
  mantis-common/src/main/java/io/mantisrx/common/metrics/Metrics.java
  mantis-common/src/main/java/io/mantisrx/common/metrics/Timer.java
  mantis-common/src/main/java/io/mantisrx/common/metrics/spectator/TimerImpl.java
Labels: enhancement

#73 Use timer for commit latency.
  mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/IcebergCommitterStage.java
  mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/metrics/CommitterMetrics.java
Labels: enhancement

#74 Update pmd version.
  gradle/check.gradle
Labels: bug
