Repository Netflix/mantis, pull requests merged in 2021-03, with the labels that each got.

#94 Upgrade nebula.netflixoss to replace bintray publication and replace TravisCI with Github Actions
  .github/workflows/nebula-ci.yml
  .github/workflows/nebula-publish.yml
  .github/workflows/nebula-snapshot.yml
  .travis.yml
  build.gradle
  buildViaTravis.sh
  gradle/wrapper/gradle-wrapper.properties
  mantis-examples/mantis-examples-core/build.gradle
  mantis-examples/mantis-examples-groupby-sample/build.gradle
  mantis-examples/mantis-examples-jobconnector-sample/build.gradle
  mantis-examples/mantis-examples-mantis-publish-sample/build.gradle
  mantis-examples/mantis-examples-mantis-publish-web-sample/build.gradle
  mantis-examples/mantis-examples-synthetic-sourcejob/build.gradle
  mantis-examples/mantis-examples-twitter-sample/build.gradle
  mantis-examples/mantis-examples-wordcount/build.gradle
  mantis-server/mantis-server-worker/build.gradle
  mantis-shaded/build.gradle
Labels: enhancement

#95 Add release drafter github action.
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation, enhancement

#96 Replace jcenter with maven central
  build.gradle
  mantis-examples/mantis-examples-mantis-publish-sample/build.gradle
  mantis-examples/mantis-examples-mantis-publish-web-sample/build.gradle
Labels: enhancement, good first issue

#97 Increment mantisEventsDropped metric when there is an exception during processing, create new Map in Event by default
  mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/EventDrainer.java
  mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/api/Event.java
  mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/metrics/StreamMetrics.java
Labels: enhancement
